# docker-compose.yml
version: '3.8'

services:
  ml-api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - API_KEY=${API_KEY:-your-secret-key-here}
      - LOG_LEVEL=INFO
      - FLASK_ENV=production
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  # Optional: Add Redis for rate limiting storage
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped