# swagger.yaml
openapi: 3.0.0
info:
  title: ML Model Prediction API
  description: API for making predictions with a trained machine learning model
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Development server
  - url: https://api.yourdomain.com
    description: Production server
tags:
  - name: Predictions
    description: Prediction operations
  - name: Monitoring
    description: Health monitoring endpoints
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    PredictionRequest:
      type: object
      required:
        - features
      properties:
        features:
          type: array
          items:
            type: number
          example: [5.1, 3.5, 1.4, 0.2]
    PredictionResponse:
      type: object
      properties:
        prediction:
          type: integer
        confidence:
          type: array
          items:
            type: number
        timestamp:
          type: string
    ErrorResponse:
      type: object
      properties:
        error:
          type: string